uas-studi-kasus/src/routes/web.php
<?php

Route::get('/getDua', 'App\Http\Controllers\Admin\InputDataController@getDua')->name('getDua');
Route::get('/getTiga', 'App\Http\Controllers\Admin\InputDataController@getTiga')->name('getTiga');
Route::get('/getEmpat', 'App\Http\Controllers\Admin\InputDataController@getEmpat')->name('getEmpat');


Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Team
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    // Data Satu
    Route::delete('data-satus/destroy', 'DataSatuController@massDestroy')->name('data-satus.massDestroy');
    Route::post('data-satus/parse-csv-import', 'DataSatuController@parseCsvImport')->name('data-satus.parseCsvImport');
    Route::post('data-satus/process-csv-import', 'DataSatuController@processCsvImport')->name('data-satus.processCsvImport');
    Route::resource('data-satus', 'DataSatuController');

    // Data Dua
    Route::delete('data-duas/destroy', 'DataDuaController@massDestroy')->name('data-duas.massDestroy');
    Route::post('data-duas/parse-csv-import', 'DataDuaController@parseCsvImport')->name('data-duas.parseCsvImport');
    Route::post('data-duas/process-csv-import', 'DataDuaController@processCsvImport')->name('data-duas.processCsvImport');
    Route::resource('data-duas', 'DataDuaController');

    // Data Tiga
    Route::delete('data-tigas/destroy', 'DataTigaController@massDestroy')->name('data-tigas.massDestroy');
    Route::post('data-tigas/parse-csv-import', 'DataTigaController@parseCsvImport')->name('data-tigas.parseCsvImport');
    Route::post('data-tigas/process-csv-import', 'DataTigaController@processCsvImport')->name('data-tigas.processCsvImport');
    Route::resource('data-tigas', 'DataTigaController');

    // Data Empat
    Route::delete('data-empats/destroy', 'DataEmpatController@massDestroy')->name('data-empats.massDestroy');
    Route::post('data-empats/parse-csv-import', 'DataEmpatController@parseCsvImport')->name('data-empats.parseCsvImport');
    Route::post('data-empats/process-csv-import', 'DataEmpatController@processCsvImport')->name('data-empats.processCsvImport');
    Route::resource('data-empats', 'DataEmpatController');

    // Input Data
    Route::delete('input-datas/destroy', 'InputDataController@massDestroy')->name('input-datas.massDestroy');
    Route::post('input-datas/parse-csv-import', 'InputDataController@parseCsvImport')->name('input-datas.parseCsvImport');
    Route::post('input-datas/process-csv-import', 'InputDataController@processCsvImport')->name('input-datas.processCsvImport');
    Route::resource('input-datas', 'InputDataController');

    Route::get('team-members', 'TeamMembersController@index')->name('team-members.index');
    Route::post('team-members', 'TeamMembersController@invite')->name('team-members.invite');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

uas-studi-kasus/src/app/Models/DataSatu.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class DataSatu extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use HasFactory;

    public $table = 'data_satus';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'nama',
        'created_at',
        'updated_at',
        'deleted_at',
        'team_id',
    ];

    public function dataSatuInputDatas()
    {
        return $this->belongsToMany(InputData::class);
    }

    public function team()
    {
        return $this->belongsTo(Team::class, 'team_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

uas-studi-kasus/src/app/Http/Controllers/Admin/DataSatuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyDataSatuRequest;
use App\Http\Requests\StoreDataSatuRequest;
use App\Http\Requests\UpdateDataSatuRequest;
use App\Models\DataSatu;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class DataSatuController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('data_satu_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = DataSatu::with(['team'])->select(sprintf('%s.*', (new DataSatu())->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = 'data_satu_show';
                $editGate = 'data_satu_edit';
                $deleteGate = 'data_satu_delete';
                $crudRoutePart = 'data-satus';

                return view('partials.datatablesActions', compact(
                'viewGate',
                'editGate',
                'deleteGate',
                'crudRoutePart',
                'row'
            ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : '';
            });
            $table->editColumn('nama', function ($row) {
                return $row->nama ? $row->nama : '';
            });

            $table->rawColumns(['actions', 'placeholder']);

            return $table->make(true);
        }

        return view('admin.dataSatus.index');
    }

    public function create()
    {
        abort_if(Gate::denies('data_satu_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.dataSatus.create');
    }

    public function store(StoreDataSatuRequest $request)
    {
        $dataSatu = DataSatu::create($request->all());

        return redirect()->route('admin.data-satus.index');
    }

    public function edit(DataSatu $dataSatu)
    {
        abort_if(Gate::denies('data_satu_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $dataSatu->load('team');

        return view('admin.dataSatus.edit', compact('dataSatu'));
    }

    public function update(UpdateDataSatuRequest $request, DataSatu $dataSatu)
    {
        $dataSatu->update($request->all());

        return redirect()->route('admin.data-satus.index');
    }

    public function show(DataSatu $dataSatu)
    {
        abort_if(Gate::denies('data_satu_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $dataSatu->load('team', 'dataSatuInputDatas');

        return view('admin.dataSatus.show', compact('dataSatu'));
    }

    public function destroy(DataSatu $dataSatu)
    {
        abort_if(Gate::denies('data_satu_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $dataSatu->delete();

        return back();
    }

    public function massDestroy(MassDestroyDataSatuRequest $request)
    {
        DataSatu::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

uas-studi-kasus/src/resources/views/admin/dataSatus/relationships/dataSatuInputDatas.blade.php
@can('input_data_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.input-datas.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.inputData.title_singular') }}
            </a>
        </div>
    </div>
@endcan

<div class="card">
    <div class="card-header">
        {{ trans('cruds.inputData.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-dataSatuInputDatas">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.inputData.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.inputData.fields.nama_input_proses_data') }}
                        </th>
                        <th>
                            {{ trans('cruds.inputData.fields.data_satu') }}
                        </th>
                        <th>
                            {{ trans('cruds.inputData.fields.data_dua') }}
                        </th>
                        <th>
                            {{ trans('cruds.inputData.fields.data_tiga') }}
                        </th>
                        <th>
                            {{ trans('cruds.inputData.fields.data_empat') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($inputDatas as $key => $inputData)
                        <tr data-entry-id="{{ $inputData->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $inputData->id ?? '' }}
                            </td>
                            <td>
                                {{ $inputData->nama_input_proses_data ?? '' }}
                            </td>
                            <td>
                                @foreach($inputData->data_satus as $key => $item)
                                    <span class="badge badge-info">{{ $item->nama }}</span>
                                @endforeach
                            </td>
                            <td>
                                @foreach($inputData->data_duas as $key => $item)
                                    <span class="badge badge-info">{{ $item->nama }}</span>
                                @endforeach
                            </td>
                            <td>
                                @foreach($inputData->data_tigas as $key => $item)
                                    <span class="badge badge-info">{{ $item->nama }}</span>
                                @endforeach
                            </td>
                            <td>
                                @foreach($inputData->data_empats as $key => $item)
                                    <span class="badge badge-info">{{ $item->nama }}</span>
                                @endforeach
                            </td>
                            <td>
                                @can('input_data_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.input-datas.show', $inputData->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('input_data_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.input-datas.edit', $inputData->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('input_data_delete')
                                    <form action="{{ route('admin.input-datas.destroy', $inputData->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('input_data_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.input-datas.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'asc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-dataSatuInputDatas:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection