uas-studi-kasus/src/routes/web.php
<?php

Route::get('/getDua', 'App\Http\Controllers\Admin\InputDataController@getDua')->name('getDua');
Route::get('/getTiga', 'App\Http\Controllers\Admin\InputDataController@getTiga')->name('getTiga');
Route::get('/getEmpat', 'App\Http\Controllers\Admin\InputDataController@getEmpat')->name('getEmpat');


Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Team
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    // Data Satu
    Route::delete('data-satus/destroy', 'DataSatuController@massDestroy')->name('data-satus.massDestroy');
    Route::post('data-satus/parse-csv-import', 'DataSatuController@parseCsvImport')->name('data-satus.parseCsvImport');
    Route::post('data-satus/process-csv-import', 'DataSatuController@processCsvImport')->name('data-satus.processCsvImport');
    Route::resource('data-satus', 'DataSatuController');

    // Data Dua
    Route::delete('data-duas/destroy', 'DataDuaController@massDestroy')->name('data-duas.massDestroy');
    Route::post('data-duas/parse-csv-import', 'DataDuaController@parseCsvImport')->name('data-duas.parseCsvImport');
    Route::post('data-duas/process-csv-import', 'DataDuaController@processCsvImport')->name('data-duas.processCsvImport');
    Route::resource('data-duas', 'DataDuaController');

    // Data Tiga
    Route::delete('data-tigas/destroy', 'DataTigaController@massDestroy')->name('data-tigas.massDestroy');
    Route::post('data-tigas/parse-csv-import', 'DataTigaController@parseCsvImport')->name('data-tigas.parseCsvImport');
    Route::post('data-tigas/process-csv-import', 'DataTigaController@processCsvImport')->name('data-tigas.processCsvImport');
    Route::resource('data-tigas', 'DataTigaController');

    // Data Empat
    Route::delete('data-empats/destroy', 'DataEmpatController@massDestroy')->name('data-empats.massDestroy');
    Route::post('data-empats/parse-csv-import', 'DataEmpatController@parseCsvImport')->name('data-empats.parseCsvImport');
    Route::post('data-empats/process-csv-import', 'DataEmpatController@processCsvImport')->name('data-empats.processCsvImport');
    Route::resource('data-empats', 'DataEmpatController');

    // Input Data
    Route::delete('input-datas/destroy', 'InputDataController@massDestroy')->name('input-datas.massDestroy');
    Route::post('input-datas/parse-csv-import', 'InputDataController@parseCsvImport')->name('input-datas.parseCsvImport');
    Route::post('input-datas/process-csv-import', 'InputDataController@processCsvImport')->name('input-datas.processCsvImport');
    Route::resource('input-datas', 'InputDataController');

    Route::get('team-members', 'TeamMembersController@index')->name('team-members.index');
    Route::post('team-members', 'TeamMembersController@invite')->name('team-members.invite');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

uas-studi-kasus/src/resources/views/partials/datatablesActions.blade.php
@can($viewGate)
    <a class="btn btn-xs btn-primary" href="{{ route('admin.' . $crudRoutePart . '.show', $row->id) }}">
        {{ trans('global.view') }}
    </a>
@endcan
@can($editGate)
    <a class="btn btn-xs btn-info" href="{{ route('admin.' . $crudRoutePart . '.edit', $row->id) }}">
        {{ trans('global.edit') }}
    </a>
@endcan
@can($deleteGate)
    <form action="{{ route('admin.' . $crudRoutePart . '.destroy', $row->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
    </form>
@endcan

uas-studi-kasus/src/resources/views/partials/menu.blade.php
<div id="sidebar" class="c-sidebar c-sidebar-fixed c-sidebar-lg-show">

    <div class="c-sidebar-brand d-md-down-none">
        <a class="c-sidebar-brand-full h4" href="#">
            {{ trans('panel.site_title') }}
        </a>
    </div>

    <ul class="c-sidebar-nav">
        <li class="c-sidebar-nav-item">
            <a href="{{ route("admin.home") }}" class="c-sidebar-nav-link">
                <i class="c-sidebar-nav-icon fas fa-fw fa-tachometer-alt">

                </i>
                {{ trans('global.dashboard') }}
            </a>
        </li>
        @can('user_management_access')
            <li class="c-sidebar-nav-dropdown {{ request()->is("admin/permissions*") ? "c-show" : "" }} {{ request()->is("admin/roles*") ? "c-show" : "" }} {{ request()->is("admin/users*") ? "c-show" : "" }} {{ request()->is("admin/teams*") ? "c-show" : "" }}">
                <a class="c-sidebar-nav-dropdown-toggle" href="#">
                    <i class="fa-fw fas fa-users c-sidebar-nav-icon">

                    </i>
                    {{ trans('cruds.userManagement.title') }}
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                    @can('permission_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.permissions.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/permissions") || request()->is("admin/permissions/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-unlock-alt c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.permission.title') }}
                            </a>
                        </li>
                    @endcan
                    @can('role_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.roles.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/roles") || request()->is("admin/roles/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-briefcase c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.role.title') }}
                            </a>
                        </li>
                    @endcan
                    @can('user_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.users.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/users") || request()->is("admin/users/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-user c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.user.title') }}
                            </a>
                        </li>
                    @endcan
                    @can('team_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.teams.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/teams") || request()->is("admin/teams/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-users c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.team.title') }}
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
        @endcan
        @can('master_data_access')
            <li class="c-sidebar-nav-dropdown {{ request()->is("admin/data-satus*") ? "c-show" : "" }} {{ request()->is("admin/data-duas*") ? "c-show" : "" }} {{ request()->is("admin/data-tigas*") ? "c-show" : "" }} {{ request()->is("admin/data-empats*") ? "c-show" : "" }}">
                <a class="c-sidebar-nav-dropdown-toggle" href="#">
                    <i class="fa-fw fas fa-cogs c-sidebar-nav-icon">

                    </i>
                    {{ trans('cruds.masterData.title') }}
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                    @can('data_satu_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.data-satus.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/data-satus") || request()->is("admin/data-satus/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-cogs c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.dataSatu.title') }}
                            </a>
                        </li>
                    @endcan
                    @can('data_dua_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.data-duas.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/data-duas") || request()->is("admin/data-duas/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-cogs c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.dataDua.title') }}
                            </a>
                        </li>
                    @endcan
                    @can('data_tiga_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.data-tigas.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/data-tigas") || request()->is("admin/data-tigas/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-cogs c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.dataTiga.title') }}
                            </a>
                        </li>
                    @endcan
                    @can('data_empat_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.data-empats.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/data-empats") || request()->is("admin/data-empats/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-cogs c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.dataEmpat.title') }}
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
        @endcan
        @can('proses_data_access')
            <li class="c-sidebar-nav-dropdown {{ request()->is("admin/input-datas*") ? "c-show" : "" }}">
                <a class="c-sidebar-nav-dropdown-toggle" href="#">
                    <i class="fa-fw fas fa-cogs c-sidebar-nav-icon">

                    </i>
                    {{ trans('cruds.prosesData.title') }}
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                    @can('input_data_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.input-datas.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/input-datas") || request()->is("admin/input-datas/*") ? "c-active" : "" }}">
                                <i class="fa-fw fas fa-cogs c-sidebar-nav-icon">

                                </i>
                                {{ trans('cruds.inputData.title') }}
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
        @endcan
        @if(\Illuminate\Support\Facades\Schema::hasColumn('teams', 'owner_id') && \App\Models\Team::where('owner_id', auth()->user()->id)->exists())
            <li class="c-sidebar-nav-item">
                <a class="{{ request()->is("admin/team-members") || request()->is("admin/team-members/*") ? "c-active" : "" }} c-sidebar-nav-link" href="{{ route("admin.team-members.index") }}">
                    <i class="c-sidebar-nav-icon fa-fw fa fa-users">
                    </i>
                    <span>{{ trans("global.team-members") }}</span>
                </a>
            </li>
        @endif
        @if(file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php')))
            @can('profile_password_edit')
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link {{ request()->is('profile/password') || request()->is('profile/password/*') ? 'c-active' : '' }}" href="{{ route('profile.password.edit') }}">
                        <i class="fa-fw fas fa-key c-sidebar-nav-icon">
                        </i>
                        {{ trans('global.change_password') }}
                    </a>
                </li>
            @endcan
        @endif
        <li class="c-sidebar-nav-item">
            <a href="#" class="c-sidebar-nav-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                <i class="c-sidebar-nav-icon fas fa-fw fa-sign-out-alt">

                </i>
                {{ trans('global.logout') }}
            </a>
        </li>
    </ul>

</div>