uas-studi-kasus/src/routes/web.php
<?php

Route::get('/getDua', 'App\Http\Controllers\Admin\InputDataController@getDua')->name('getDua');
Route::get('/getTiga', 'App\Http\Controllers\Admin\InputDataController@getTiga')->name('getTiga');
Route::get('/getEmpat', 'App\Http\Controllers\Admin\InputDataController@getEmpat')->name('getEmpat');


Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Team
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    // Data Satu
    Route::delete('data-satus/destroy', 'DataSatuController@massDestroy')->name('data-satus.massDestroy');
    Route::post('data-satus/parse-csv-import', 'DataSatuController@parseCsvImport')->name('data-satus.parseCsvImport');
    Route::post('data-satus/process-csv-import', 'DataSatuController@processCsvImport')->name('data-satus.processCsvImport');
    Route::resource('data-satus', 'DataSatuController');

    // Data Dua
    Route::delete('data-duas/destroy', 'DataDuaController@massDestroy')->name('data-duas.massDestroy');
    Route::post('data-duas/parse-csv-import', 'DataDuaController@parseCsvImport')->name('data-duas.parseCsvImport');
    Route::post('data-duas/process-csv-import', 'DataDuaController@processCsvImport')->name('data-duas.processCsvImport');
    Route::resource('data-duas', 'DataDuaController');

    // Data Tiga
    Route::delete('data-tigas/destroy', 'DataTigaController@massDestroy')->name('data-tigas.massDestroy');
    Route::post('data-tigas/parse-csv-import', 'DataTigaController@parseCsvImport')->name('data-tigas.parseCsvImport');
    Route::post('data-tigas/process-csv-import', 'DataTigaController@processCsvImport')->name('data-tigas.processCsvImport');
    Route::resource('data-tigas', 'DataTigaController');

    // Data Empat
    Route::delete('data-empats/destroy', 'DataEmpatController@massDestroy')->name('data-empats.massDestroy');
    Route::post('data-empats/parse-csv-import', 'DataEmpatController@parseCsvImport')->name('data-empats.parseCsvImport');
    Route::post('data-empats/process-csv-import', 'DataEmpatController@processCsvImport')->name('data-empats.processCsvImport');
    Route::resource('data-empats', 'DataEmpatController');

    // Input Data
    Route::delete('input-datas/destroy', 'InputDataController@massDestroy')->name('input-datas.massDestroy');
    Route::post('input-datas/parse-csv-import', 'InputDataController@parseCsvImport')->name('input-datas.parseCsvImport');
    Route::post('input-datas/process-csv-import', 'InputDataController@processCsvImport')->name('input-datas.processCsvImport');
    Route::resource('input-datas', 'InputDataController');

    Route::get('team-members', 'TeamMembersController@index')->name('team-members.index');
    Route::post('team-members', 'TeamMembersController@invite')->name('team-members.invite');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

uas-studi-kasus/src/app/Models/DataEmpat.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class DataEmpat extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use HasFactory;

    public $table = 'data_empats';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'nama',
        'created_at',
        'updated_at',
        'deleted_at',
        'team_id',
    ];

    public function dataEmpatInputDatas()
    {
        return $this->belongsToMany(InputData::class);
    }

    public function team()
    {
        return $this->belongsTo(Team::class, 'team_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

uas-studi-kasus/src/app/Http/Controllers/Admin/DataEmpatController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyDataEmpatRequest;
use App\Http\Requests\StoreDataEmpatRequest;
use App\Http\Requests\UpdateDataEmpatRequest;
use App\Models\DataEmpat;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class DataEmpatController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('data_empat_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = DataEmpat::with(['team'])->select(sprintf('%s.*', (new DataEmpat())->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = 'data_empat_show';
                $editGate = 'data_empat_edit';
                $deleteGate = 'data_empat_delete';
                $crudRoutePart = 'data-empats';

                return view('partials.datatablesActions', compact(
                'viewGate',
                'editGate',
                'deleteGate',
                'crudRoutePart',
                'row'
            ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : '';
            });
            $table->editColumn('nama', function ($row) {
                return $row->nama ? $row->nama : '';
            });

            $table->rawColumns(['actions', 'placeholder']);

            return $table->make(true);
        }

        return view('admin.dataEmpats.index');
    }

    public function create()
    {
        abort_if(Gate::denies('data_empat_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.dataEmpats.create');
    }

    public function store(StoreDataEmpatRequest $request)
    {
        $dataEmpat = DataEmpat::create($request->all());

        return redirect()->route('admin.data-empats.index');
    }

    public function edit(DataEmpat $dataEmpat)
    {
        abort_if(Gate::denies('data_empat_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $dataEmpat->load('team');

        return view('admin.dataEmpats.edit', compact('dataEmpat'));
    }

    public function update(UpdateDataEmpatRequest $request, DataEmpat $dataEmpat)
    {
        $dataEmpat->update($request->all());

        return redirect()->route('admin.data-empats.index');
    }

    public function show(DataEmpat $dataEmpat)
    {
        abort_if(Gate::denies('data_empat_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $dataEmpat->load('team', 'dataEmpatInputDatas');

        return view('admin.dataEmpats.show', compact('dataEmpat'));
    }

    public function destroy(DataEmpat $dataEmpat)
    {
        abort_if(Gate::denies('data_empat_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $dataEmpat->delete();

        return back();
    }

    public function massDestroy(MassDestroyDataEmpatRequest $request)
    {
        DataEmpat::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

uas-studi-kasus/src/resources/views/admin/dataEmpats/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.dataEmpat.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.data-empats.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="nama">{{ trans('cruds.dataEmpat.fields.nama') }}</label>
                <input class="form-control {{ $errors->has('nama') ? 'is-invalid' : '' }}" type="text" name="nama" id="nama" value="{{ old('nama', '') }}">
                @if($errors->has('nama'))
                    <div class="invalid-feedback">
                        {{ $errors->first('nama') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.dataEmpat.fields.nama_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

uas-studi-kasus/src/resources/views/admin/dataEmpats/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.dataEmpat.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.data-empats.update", [$dataEmpat->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="nama">{{ trans('cruds.dataEmpat.fields.nama') }}</label>
                <input class="form-control {{ $errors->has('nama') ? 'is-invalid' : '' }}" type="text" name="nama" id="nama" value="{{ old('nama', $dataEmpat->nama) }}">
                @if($errors->has('nama'))
                    <div class="invalid-feedback">
                        {{ $errors->first('nama') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.dataEmpat.fields.nama_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

uas-studi-kasus/src/resources/views/admin/dataEmpats/index.blade.php
@extends('layouts.admin')
@section('content')
@can('data_empat_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.data-empats.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.dataEmpat.title_singular') }}
            </a>
            <button class="btn btn-warning" data-toggle="modal" data-target="#csvImportModal">
                {{ trans('global.app_csvImport') }}
            </button>
            @include('csvImport.modal', ['model' => 'DataEmpat', 'route' => 'admin.data-empats.parseCsvImport'])
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.dataEmpat.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-DataEmpat">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.dataEmpat.fields.id') }}
                    </th>
                    <th>
                        {{ trans('cruds.dataEmpat.fields.nama') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('data_empat_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.data-empats.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.data-empats.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'nama', name: 'nama' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    orderCellsTop: true,
    order: [[ 1, 'asc' ]],
    pageLength: 100,
  };
  let table = $('.datatable-DataEmpat').DataTable(dtOverrideGlobals);
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
});

</script>
@endsection

uas-studi-kasus/src/resources/views/admin/dataEmpats/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.dataEmpat.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.data-empats.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.dataEmpat.fields.id') }}
                        </th>
                        <td>
                            {{ $dataEmpat->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.dataEmpat.fields.nama') }}
                        </th>
                        <td>
                            {{ $dataEmpat->nama }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.data-empats.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        {{ trans('global.relatedData') }}
    </div>
    <ul class="nav nav-tabs" role="tablist" id="relationship-tabs">
        <li class="nav-item">
            <a class="nav-link" href="#data_empat_input_datas" role="tab" data-toggle="tab">
                {{ trans('cruds.inputData.title') }}
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" role="tabpanel" id="data_empat_input_datas">
            @includeIf('admin.dataEmpats.relationships.dataEmpatInputDatas', ['inputDatas' => $dataEmpat->dataEmpatInputDatas])
        </div>
    </div>
</div>

@endsection